name: Publish snapshots to maven

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 0.*
      - upload-jar-files

jobs:
  build-and-publish-snapshots:
    strategy:
      fail-fast: false
#    if: github.repository == 'opensearch-project/opensearch-spark'
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Set up SBT
        uses: sbt/setup-sbt@v1

      - name: Publish to Local Maven
        run: |
          sbt standaloneCosmetic/publishM2
          sbt sparkPPLCosmetic/publishM2
          sbt sparkSqlApplicationCosmetic/publishM2

      - uses: actions/checkout@v3
        with:
          repository: 'opensearch-project/opensearch-build-libraries'
          path: 'build'

      - name: generate sha and md5
        run: |
          for i in `find ${HOME}/.m2/repository/org/opensearch/ -name "*.pom" -type f`; do sha512sum "$i" | awk '{print $1}' >> "$i.sha512"; done
          for i in `find ${HOME}/.m2/repository/org/opensearch/ -name "*.jar" -type f`; do sha512sum "$i" | awk '{print $1}' >> "$i.sha512"; done
          for i in `find ${HOME}/.m2/repository/org/opensearch/ -name "*.pom" -type f`; do sha256sum "$i" | awk '{print $1}' >> "$i.sha256"; done
          for i in `find ${HOME}/.m2/repository/org/opensearch/ -name "*.jar" -type f`; do sha256sum "$i" | awk '{print $1}' >> "$i.sha256"; done

      - name: Get credentials and publish snapshots to maven
        run: |
          cd build/resources/publish/
          cp -a $HOME/.m2/repository/* ./
          find ./ -type f -name "*SNAPSHOT.jar" -exec cp {}  \;

      - name: Upload jar files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jar-files
          path: build/resources/publish/**/*.jar
